### ISSUE TITLE
Unable to bind Space-prefixed commentary command

### ISSUE THREAD

**Issue by ivanbrennan** [linktohack/evil-commentary#10]
There's a very good chance I'm just doing this wrong, as I'm still learning my way around Emacs keymaps, but I'm having a hard time building the binding I want. I'd like to  bind `SPC ;` to evil-commentary, so
`SPC ; ;` => comment out current line
`SPC ; a p` => comment out current paragraph
...

What I've tried so far:

``` emacs-lisp
(evil-define-key 'normal evil-commentary-mode-map (kbd "SPC ;") 'evil-commentary)

;; using general.el https://github.com/noctuid/general.el
(general-define-key :states '(normal visual)
                    :keymaps 'evil-commentary-mode-map
                    :prefix "SPC"
                    ";" 'evil-commentary)
```

With either approach, when I type `SPC ;` the echo area reports: `No command bound to  ;`

While trying to debug, I tried the example binding from the README,

``` emacs-lisp
(evil-define-key 'normal evil-commentary-mode-map ",c" 'evil-commentary)
```

and found this works for sequences like `,cj` or `,cap`, but typing `,cc` just echos `Quit` in the echo area, rather than commenting out the current line.

Any help would be much appreciated.

**Comment by linktohack** [comment]
Hi @ivanbrennan, `evil-commentary` is an operator, so it accepts a motion command before executing. In your case it's `evil-repeat-find-char` (<kbd>;</kbd>).

If you are using `spacemacs` then there is a configured layer already: https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bvim/evil-commentary/packages.el

If you are not using `spacemacs`, you can try to unbind <kbd>SPC</kbd>, <kbd>,</kbd> & <kbd>;</kbd> first,  have a look at `evil-space` revive `evil-repeat-find-char` etc.

About the example in README, you are right that it is not working with vanilla Emacs, (but it does with my setup (https://gist.github.com/linktohack/30b1122f1efdafe3f7c7). I will have a look and let you know, for now can you try <kbd>,c,</kbd> to see if it work?

**Comment by linktohack** [comment]
Ok, found it. For <kbd>,cc</kbd> works, please add
```
(define-key evil-motion-state-map "," nil)
(evil-define-key 'normal evil-commentary-mode-map ",c" 'evil-commentary)
```
 to your `init.el`

**Comment by linktohack** [comment]
Clean up, feel free to reopen...
