### ISSUE TITLE
How to give preference to line-wise (//) comments over region comments (/* */) in js

### ISSUE THREAD

**Issue by hbaughman** [linktohack/evil-commentary#14]
I would prefer to use line-wise comments (`//`) in my JS over region-based comments (`/* */`) when executing `evil-commentary-line`. I didn't see any configuration option to this effect. Is it possible?

**Comment by linktohack** [comment]
Looks like a mode/configuration conflict @hbaughman, both <kbd>3gcc</kbd> and <kbd>gcap</kbd> give me line-wise comment for `js-mode` and `js2-mode`

**Comment by linktohack** [comment]
Closing as it does not seem to be related to `evil-commentary`

**Comment by hbaughman** [comment]
Yup. Seems to be related to web-mode. Thanks for your help.
