### ISSUE TITLE
Is the minor-mode really necessary?

### ISSUE THREAD

**Issue by Ambrevar** [linktohack/evil-commentary#18]
Having a minor seems to override bindings made to some major mode maps (e.g. `gc`).
Wouldn't it be possible to modify evil's global normal map instead?

If not, I'd also love the possibility to customize the minor mode lighter, just light `undo-tree-mode-lighter` is for.

**Comment by linktohack** [comment]
You may want this? :)

https://gist.github.com/linktohack/30b1122f1efdafe3f7c7#file-init-el-L60-L61

**Comment by Ambrevar** [comment]
I do not wish to use `diminish`. Besides I think it's good practice to make the lighter a variable. It's only one line s-exp to add :)

That does not answer my first question though... Why defining a minor mode in the first place?

**Comment by linktohack** [comment]
>Why defining a minor mode in the first place?

To be self-contained. A user can try the minor mode; if he is not happy he can just disable it without having to restart the editor. If you don't like the minor mode, just define the map you want.

https://github.com/linktohack/evil-commentary/blob/master/evil-commentary.el#L114-L115

**Comment by Ambrevar** [comment]
Right, I thought the manual setup would be somewhat longer, it's actually very simple.  Case closed.  Sorry for the needless noise.
