### ISSUE TITLE
`gcc` not working anymore?

### ISSUE THREAD

**Issue by rafaelrinaldi** [linktohack/evil-commentary#19]
Recently after upgrading Spacemacs and the list of plugins, whenever I hit `gcc` I get the following message:

>Symbol's value as variable is void: evilnc-comment-operator

Any ideas why this is happening?

**Comment by linktohack** [comment]
> evilnc-comment-operator

Looks like you are using evil-nerd-commenter. Please have a look at the evil-commentary layer: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bvim/evil-commentary

**Comment by rafaelrinaldi** [comment]
Cleaning up `.emacs.d` and reinstalling packages all over again did the trick.
