### ISSUE TITLE
How to do un-comment?

### ISSUE THREAD

**Issue by liujoey** [linktohack/evil-commentary#2]
tpope's plugin works as a toggle. So if you run gcc on a commented line, it un-comment it. Is this implemented in evil-commentary?

edit: uncomment works in javascript, but does not work correctly in html file.

**Comment by linktohack** [comment]
`evil-commentary` uses `comment-or-uncomment-region` internally. It usually works fine with single major mode, but the situation is more complicated for embed code blocks inside other major mode like HTML/JavaScript/CSS as Emacs syntax doesn't under scope.

I tried with `web-mode` and it seems to be able to comment/uncomment HTML part, but not JavaScript. Internally, it looks like `web-mode` use it own function `web-mode-comment-or-uncomment`.

I'm thinking of adding a custom variable to use custom comment function of current major mode. Can you please send me a portion of your code and your current major mode?

**Comment by linktohack** [comment]
@liujoey, implemented in the code (with `web-mode`), please update and check if it works for you.

**Comment by liujoey** [comment]
it works now. Great work!
