### ISSUE TITLE
Mode specific hooks

### ISSUE THREAD

**Issue by ledohod** [linktohack/evil-commentary#21]
How to disable the evil commentary mode in dired mode. If I add a hook to dired mode it disables evil commentary mode globally.

**Comment by linktohack** [comment]
Hello @arturakb , sorry for the late reply. I think the most simple way is to override your key biding in `dired-mode-hook`.

The two other solutions are 1) create a `evil-commentary-minor-mode` 2) add a variable so-called `evil-commentary-modes` and set it to something like `(not dire-mode)` etc but I'm not so motivated 🤒
