### ISSUE TITLE
How to Customize "Comment Syntax" for a particular language?

### ISSUE THREAD

**Issue by ianpan870102** [linktohack/evil-commentary#24]
In C programming mode, I'd like to use `//`, instead of the default `/* */` style of commenting. How can I go about customizing this?

**Comment by linktohack** [comment]
I guess `c-toggle-comment-style` will help.

**Comment by ianpan870102** [comment]
@linktohack Thanks! Calling `c-toggle-comment-style` indeed enables the behavior. However, I'd like to put it somewhere in my `init.el` and have the line comment style `//` enabled by default.
I tried something like:
```emacs-lisp
(use-package evil-commentary
  :after evil
  :config
  (evil-commentary-mode +1)
  (c-toggle-comment-style -1))
```
I'm using `-1` because the documentation mentioned that "Optional numeric ARG, if supplied, switches to block comment style when positive, to line comment style when negative, and just toggles it when zero or left out."

However, after this configuration in my `init.el`, I'm still having the block comment style `/* */` as my default.

**Comment by linktohack** [comment]
I think you will need a `hook`, something like this

```emacs-lisp
(add-hook 'c-mode-hook #'(lambda () (c-toggle-comment-style -1)))
````

**Comment by ianpan870102** [comment]
Thanks @linktohack ! This hooking method worked perfectly. Closing issue.
