### ISSUE TITLE
copy only the original content of a commented line?

### ISSUE THREAD

**Issue by linwaytin** [linktohack/evil-commentary#27]
First, thanks for this nice package. It is simple but provides the necessary functions. 

I'm wondering if there is a simple way to copy the original content of a commented line. For example, if the cursor is on
```elisp
;; (setq evil-commentary-mode t)
```
I want to copy only the line `(setq evil-commentary-mode t)`. I think this scenario is quite common when testing code.

I guess this is equivalent to uncomment a line, copy the line, and re-comment the line.

**Comment by linwaytin** [comment]
Yeah, I think I can make it by myself.

**Comment by linktohack** [comment]
Cool @linwaytin. I'm going to close this
