### ISSUE TITLE
Use `COMMENT` keyword on Org headings?

### ISSUE THREAD

**Issue by edgar-vincent** [linktohack/evil-commentary#28]
Hi,

Thanks a lot for this package.

When used on an Org heading, `evil-commentary/org-comment-or-uncomment-region` does not use the `COMMENT` keyword (see [this page](https://orgmode.org/org.html#Comment-Lines) in the Org manual for a description). Instead, it calls `comment-or-uncomment-region`, which simply adds a `#` at the beginning of the heading.

I believe that most users, when they comment a heading, expect to comment it out entirely, which is what the `COMMENT` keyword does, instead of commenting its own line only.

This is particularly important when exporting a buffer:

```
* This heading is exported
** So is anything 
- beneath 
- it.
```

With `comment-or-uncomment-region` on the first heading: 
```
# * This heading is NOT exported.
** But everything
- under it
- is.
```

With a `COMMENT` keyword (as inserted by `org-comment-dwim`:
```
* COMMENT This heading is NOT exported.
** Nor is anything
- under
- it.
```

What do you think? 

Thanks!

EV

**Comment by edgar-vincent** [comment]
```elisp
(defun evil-commentary/org-comment-or-uncomment-region (beg end)
  "Comment function for `org-mode'."
  (interactive "r")
  (cond ((org-in-src-block-p)
	 (evil-commentary/org-babel-do-in-edit-buffer beg end
	   (call-interactively 'evil-commentary)))
	((and (org-at-heading-p) (not mark-active))
	 (org-toggle-comment))
	(t
	 (comment-or-uncomment-region beg end))))

```

Perhaps this could do?

**Comment by linktohack** [comment]
That’s cool @edgar-vincent. Do you mind a PR? Thanks
