### ISSUE TITLE
Text objects slightly off

### ISSUE THREAD

**Issue by justmytwospence** [linktohack/evil-commentary#3]
If I am on line 30 and press `gck`, only line 29 is commented (should be 29 and 30).
If I am on line 30 and press `gcj`, only line 30 is commented (should be 30 and 31).

Is this some strange interaction with the rest of my setup, or is this a bug that everyone can replicate?

**Comment by linktohack** [comment]
Hi @justmytwospence, my guest is your configuration. Can you try to create a file named `sos.el` and start `Emacs` with `emacs -q -l /path/to/sos.el` and try again?
```lisp
;; package
(setq package-archives '(("melpa" . "http://melpa.milkbox.net/packages/")       
                         ("gnu" . "http://elpa.gnu.org/packages/")))
(setq package-enable-at-startup nil)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
;; evil
(use-package evil
  :ensure t :ensure evil-commentary
  :init
  (evil-mode)
  (evil-commentary-mode)
)
```

**Comment by justmytwospence** [comment]
Derp. Figured it out. I had these lines:

```
(define-key evil-motion-state-map "j" 'evil-next-visual-line)
(define-key evil-motion-state-map "k" 'evil-previous-visual-line)
```

I wonder how I could get that visual line behavior without messing up the text object.

**Comment by linktohack** [comment]
I supposes that's how text-object works. May be you can try to map "j" and "k" in normal state instead?
```lisp
(define-key evil-normal-state-map "j" 'evil-next-visual-line)
(define-key evil-normal-state-map "k" 'evil-previous-visual-line)
```

**Comment by linktohack** [comment]
I'm closing this as it's actually not an issue with evil-commentary.

**Comment by wbolster** [comment]
@linktohack thank you, i ran into the same issue and solved thanks to your comment.
