### ISSUE TITLE
Doesn't work for haml

### ISSUE THREAD

**Issue by lethjakman** [linktohack/evil-commentary#4]
I'm not sure if this is a problem with evil-commentary or something else, but if I try to use it in haml it will always add another comment and never remove a comment.

**Comment by linktohack** [comment]
Can you elaborate? How do you comment and un-comment without `evil-commentary`? My quick review on `haml-mode` that it doesn't using the standard `comment-or-uncomment-region` which `evil-commentary` uses. So a custom one may require, just like the case with `web-mode` ealier (This snippet is now upstream
https://github.com/linktohack/evil-commentary/blob/531a57378b54e9e2a60e0aecdca91461352cf9df/ec-mode-comment-functions.el#L3)

**Comment by linktohack** [comment]
I'm closing this as it doesn't relate directly to `evil-commentary'. Feel free to re-open it with more description...
