### ISSUE TITLE
comment-indent

### ISSUE THREAD

**Issue by lunaryorn** [linktohack/evil-commentary#6]
Emacs provides `comment-indent`, which creates an inline comment at `comment-column`.  Does this plugin provide a similar feature?

**Comment by linktohack** [comment]
It doesn't at the moment. If you were interested in aligning comments, I would suggest you to have a dedicated binding for `align-regex`, it's very powerful and works ubiquitously not just for comment.

**Comment by lunaryorn** [comment]
@linktohack I'm aware of `align-regex`, but it's not exactly equivalent.  Thank you for your help, though, and many thanks for this great package :)

**Comment by linktohack** [comment]
Thanks for the compliment, @lunaryorn. I'm closing the issue, feel free to reopen if you found it's essential to have this feature.
