### ISSUE TITLE
Comment and move down

### ISSUE THREAD

**Issue by felixSchl** [linktohack/evil-commentary#7]
It would be great to have the ability to quickly comment a line and move to the next line. I thought it would be easy enough but I found that combining operators in evil is [not so trivial](http://superuser.com/questions/469327/combining-two-operators-in-evil-mode-emacs).

Do you have any thoughts on this?

This is what I have got so far, **but it does not work**:

```elisp
  (defun comment-and-move ()
    (interactive)
    (evil-commentary-line) ;; this command needs input - but what?
    (evil-next-line 1))
  (evil-global-set-key 'normal "`" 'comment-and-move)
```

**Comment by linktohack** [comment]
What about something like this?

```emacs-lisp
(defun comment-and-move ()
  (interactive)
  (call-interactively 'evil-commentary-line)
  (evil-next-line 1))
```

**Comment by linktohack** [comment]
The idea of `evil-commentary-line` is that it allows us comment multiple line at one, so an interactive form maybe better:
```emacs-lisp
(defun comment-and-move (count)
  (interactive "p")
  (dotimes (i count)
    (call-interactively 'evil-commentary-line))
  (evil-next-line count))
```
That way you can still continue doing something like <kbd>C-u 3 M-x comment-and-move</kbd>

**Comment by felixSchl** [comment]
This works! Thank you so much for taking the time to help me out, I would have never guessed that.
