### ISSUE TITLE
Evil Commentary does not work on selections

### ISSUE THREAD

**Issue by jgkamat** [linktohack/evil-commentary#8]
For example, I cannot line select a few lines, then press `gc` to comment the selection. I'm pretty sure this was available in vim-commentary.

**Comment by linktohack** [comment]
Hi @jgkamat, my guest is your configuration. Can you try to create a file named sos.el and start Emacs with emacs -q -l /path/to/sos.el and try again?

```emacs-lisp
;; package
(setq package-archives '(("melpa" . "http://melpa.milkbox.net/packages/")       
                         ("gnu" . "http://elpa.gnu.org/packages/")))
(setq package-enable-at-startup nil)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
;; evil
(use-package evil
  :ensure t :ensure evil-commentary
  :init
  (evil-mode)
  (evil-commentary-mode)
)
```

**Comment by jgkamat** [comment]
Yup, this was an issue with my config. Turns out the eyebrowse package has some conflicting keybindings. 

Thanks for your time!
