### ISSUE TITLE
Missing the ability to uncomment adjacent commented lines with `gcgc`

### ISSUE THREAD

**Issue by ivanbrennan** [linktohack/evil-commentary#9]
[vim-commentary](https://github.com/tpope/vim-commentary) will uncomment a set of adjacent commented lines with `gcgc`. How feasible would it be to add this to evil-commentary?

**Comment by linktohack** [comment]
Is this something like <kbd>gcap</kbd>, @ivanbrennan ?

**Comment by ivanbrennan** [comment]
@linktohack It's different in that it allows for blank lines between the "adjacent" lines. So given this starting text, and cursor indicated by |
```emacs-lisp
;; '(a b)
;; '(c d) |

;; '(m n)
```
typing `gcgc` yields
```emacs-lisp
'(a b)
'(c d) |

'(m n)
```
whereas `gcap` would result in
```emacs-lisp
'(a b)
'(c d) |

;; '(m n)
```
Another example is starting with
```emacs-lisp
;; '(a b) |
;; '(c d)
'(m n)
```
Typing `gcgc` produces:
```emacs-lisp
'(a b) |
'(c d)
'(m n)
```
But `gcap` would instead produce:
```emacs-lisp
;; ;; '(a b) |
;; ;; '(c d)
;; '(m n)
```
It's useful when you have a large swaths of code you want to comment/uncomment. Visually selecting and typing `gc` comments out the non-blank lines, and `gcgc` makes it easy to uncomment them without reselecting the whole region, even if they're separated by blank lines.

**Comment by linktohack** [comment]
@ivanbrennan Looks like we need a custom text object that can make use of `evil-commentary` operator. May be something like this? :)

```emacs-lisp
(defun evil-commentary/ensure-in-comment-block (beg end forward)
  (save-excursion
    (beginning-of-line)
    (if (not (looking-at-p (concat "\\s\\*" (regexp-quote comment-start))))
        (list beg end)
      (let ((saved-beg (point))
            (saved-end (point-at-eol)))
        (catch 'bound
          (when (<= saved-beg (point-min))
            (throw 'bound (list saved-beg end)))
          (when (>= saved-end (point-max))
            (throw 'bound (list beg saved-end)))
          (if forward
              (next-line)
            (previous-line))
          (apply #'evil-commentary/ensure-in-comment-block
                 (if forward
                     (list beg saved-end forward)
                   (list saved-beg end forward))))))))

(evil-define-text-object evil-commentary/a-comment-block (count &optional beg end type)
  "A comment block"
  (let ((backward (evil-commentary/ensure-in-comment-block (point) (point) nil))
        (forward (evil-commentary/ensure-in-comment-block (point) (point) t)))
    (list (car backward) (cadr forward))))

(define-key evil-outer-text-objects-map "u" #'evil-commentary/a-comment-block)
```

Try <kbd>gcau</kbd> on a comment block to uncomment it.

**Comment by linktohack** [comment]
Clean up, feel free to reopen...
